public class Course {


    private int cid;
    // Course ID. Each course’s course ID is unique and is automatically generated by class Course. Starting from 1, each new course’s ID will increase by 1.
    private String name;
    private static int courseCnt = 1;
    // Initialized to 1, increased by 1 everytime a Course object is created

    public Course(String name){
        setName(name);
        this.cid = courseCnt;
        ++courseCnt;
    }
    // Constructor, automatically generate course ID and generate Course object according to the name provided by the user


    public int getCid(){
        return this.cid;
    }
    public String getName(){
        return this.name;
    }

    public void setName(String name){
        this.name = name;
    }
    public static int getCourseCnt(){
        return Course.courseCnt;
    }

@Override
    public String toString(){
        return "Course: "+getName()+", cid: "+getCid();
        }
    // When printing an object of this class, follow the format: "Course: %s, cid: %d" (without quotes)

}
