public class Student {
    private int sid;
    // Student ID. Each student’s student ID is unique and is automatically generated by class Student. Starting from 1, each new student’s ID will increase by 1.
    private String name;
    private static int studentCnt = 1;
    // Initialized to 1, increased by 1 everytime a Student object is created

    public Student(String name){
        setName(name);
        this.sid = studentCnt;
        ++studentCnt;
    }

    public int getSid(){
        return this.sid;
    }
    public String getName(){
        return this.name;
    }
    public void setName(String name){
        this.name = name;
    }
    public static int getStudentCnt(){
        return Student.studentCnt;
    }
    @Override
    public String toString(){
        return "Student: "+getName()+", sid: "+getSid();
    }
    // When printing an object of this class, follow the format: "Student: %s, sid: %d" (without quotes)
}
